l2chains = [    
    {name = "OP Sepolia Testnet", chainId = 11155420},
    {name = "Ink Sepolia Testnet", chainId = 763373}
]

templateName = "OPCMUpgradeV400"

# OP Sepolia Testnet
[[opcmUpgrades]]
chainId = 11155420
# prestates."1.6.1-rc.1
# https://github.com/ethereum-optimism/superchain-registry/blob/d82a61168fd1d7ef522ed8e213ce23c853031495/validation/standard/standard-prestates.toml#L6
absolutePrestate = "0x03eb07101fbdeaf3f04d9fb76526362c1eea2824e4c6e970bdb19675b72e4fc8"
# This expectedErrors are because of a bug on StandardValidatorV400
expectedValidationErrors = "PDDG-150,PLDG-150"

# Ink Sepolia Testnet
[[opcmUpgrades]]
chainId = 763373
# prestates."1.6.1-rc.1
# https://github.com/ethereum-optimism/superchain-registry/blob/d82a61168fd1d7ef522ed8e213ce23c853031495/validation/standard/standard-prestates.toml#L6

absolutePrestate = "0x03eb07101fbdeaf3f04d9fb76526362c1eea2824e4c6e970bdb19675b72e4fc8"
# This expectedErrors are because of a bug on StandardValidatorV400
expectedValidationErrors = "PDDG-150,PLDG-150"

[addresses]
OPCM = "0x831969dbff2506a5a8bdaec7ecb981b875b21001" # Freshly deployed on Sepolia
StandardValidatorV400 = "0x37FeEa021bEbFf407B18a96680909277f23845d0" # Freshly deployed on Sepolia