l2chains = [{ name = "Base Sepolia", chainId = 84532 }]
templateName = "GnosisSafeApproveHash"

safeAddressString = "BaseNestedSafe"
safeTxHash = "0x2d2e39464e4e4171eb918c5d91079f83b485b12d2fccedd3c5481b56622f6dde"