l2chains = [    
    {name = "Base Sepolia Testnet", chainId = 84532}
]

templateName = "OPCMUpgradeV400"

[[opcmUpgrades]]
chainId = 84532
# Absolute prestate needs to be changed! Not known yet.
absolutePrestate = "0x03ee2917da962ec266b091f4b62121dc9682bb0db534633707325339f99ee405"
expectedValidationErrors = ""

[addresses]
OPCM = "0x355fd2a98fc11f5e4a91d9aa4c0041d252a77583" # Freshly deployed on Sepolia
StandardValidatorV400 = "0xd0233aa63b11c2b93f68e306a16f2786fb11d0d1" # Freshly deployed on Sepolia
# Base Sepolia ProxyAdminOwner: 0x0fe884546476dDd290eC46318785046ef68a0BA9
# The get-safe.sh script will extract these addresses when signing for each owner fo the safe.
#NestedSafe1 = "0x6AF0674791925f767060Dd52f7fB20984E8639d8" # First owner on the proxy admin owner 
#NestedSafe2 = "0x646132A1667ca7aD00d36616AFBA1A28116C770A" # Second owner on the proxy admin owner
