l2chains = [    
    {name = "World Chain Sepolia Testnet", chainId = 4801}
]

templateName = "OPCMUpgradeV400"

[[opcmUpgrades]]
chainId = 4801
# Absolute prestate needs to be changed! Not known yet.
absolutePrestate = "0x03ee2917da962ec266b091f4b62121dc9682bb0db534633707325339f99ee405"
expectedValidationErrors = ""

[addresses]
OPCM = "0x355fd2a98fc11f5e4a91d9aa4c0041d252a77583" # Freshly deployed on Sepolia
StandardValidatorV400 = "0xd0233aa63b11c2b93f68e306a16f2786fb11d0d1" # Freshly deployed on Sepolia