l2chains = [    
    #{name = "OP Sepolia Testnet", chainId = 11155420}, 
    {name = "Unichain Sepolia Testnet", chainId = 1301},
    #{name = "Ink Sepolia Testnet", chainId = 763373},
    #{name = "Soneium Testnet Minato", chainId = 1946}
]

templateName = "OPCMUpgradeV400"

# OP Sepolia Testnet
#[[opcmUpgrades]]
#chainId = 11155420
# Absolute prestate needs to be changed! Not known yet.
#absolutePrestate = "0x03ee2917da962ec266b091f4b62121dc9682bb0db534633707325339f99ee405"
#expectedValidationErrors = ""

# Unichain Sepolia Testnet
[[opcmUpgrades]]
chainId = 1301
# Absolute prestate needs to be changed! Not known yet.
absolutePrestate = "0x03ee2917da962ec266b091f4b62121dc9682bb0db534633707325339f99ee405"
expectedValidationErrors = ""

# Ink Sepolia Testnet
#[[opcmUpgrades]]
#chainId = 763373
# Absolute prestate needs to be changed! Not known yet.
#absolutePrestate = "0x03ee2917da962ec266b091f4b62121dc9682bb0db534633707325339f99ee405"
#expectedValidationErrors = ""

# Soneium Testnet Minato
#[[opcmUpgrades]]
#chainId = 1946
# Absolute prestate needs to be changed! Not known yet.
#absolutePrestate = "0x03ee2917da962ec266b091f4b62121dc9682bb0db534633707325339f99ee405"
# TODO: Check why this errors get triggered and add a comment explaining why.
# I think they still are on permissioned dispute games
#expectedValidationErrors = "PDDG-120,PLDG-10"

[addresses]
OPCM = "0x355fd2a98fc11f5e4a91d9aa4c0041d252a77583" # Freshly deployed on Sepolia
StandardValidatorV400 = "0xd0233aa63b11c2b93f68e306a16f2786fb11d0d1" # Freshly deployed on Sepolia
# Unlike Unichain Mainnet, Unichain Sepolia is owned by a single (non-nested safe), which does not
# own other nested safes.
# We therefore do not override the nonce on the proxy admin owner, and do not need to specify
# the child safe addresses.